### ISSUE TITLE
create selection of people to choose from

### ISSUE THREAD

**Issue by 11bus11** [keironchaudhry/women-in-tech-hackathon#4]

**Comment by benjackson3811** [comment]
[Influencial Women Bios.docx](https://github.com/keironchaudhry/women-in-tech-hackathon/files/11002639/Influencial.Women.Bios.docx)

Please find attached 10 bio that ive prepared. 

Ive gone with the view of its better to have to many bios than too few, we may want to only have 5 or so? 

Ive broken it down to Name, background and Achievements/ Legacy/ impact.
